using Microsoft.EntityFrameworkCore;
using TechSolve.Domain.Entities;
using TechSolve.Domain.Enums;

namespace TechSolve.DataModel;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<Enquiry> Enquiries => Set<Enquiry>();
    public DbSet<BlogPost> BlogPosts => Set<BlogPost>();
    public DbSet<Service> Services => Set<Service>();
    public DbSet<WhatsAppTracking> WhatsAppTrackings => Set<WhatsAppTracking>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);
        SeedData(modelBuilder);
    }

    private static void SeedData(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Service>().HasData(
            new Service { Id=1, Slug="custom-software-development", Title="Custom Software Development", Tagline="Built for your exact requirements", ShortDescription="Bespoke applications engineered for your unique business processes — from complex enterprise workflows to greenfield SaaS platforms.", LongDescription="We design and build software that fits your business precisely — not a generic product forced to adapt. Our senior engineers work with you to map processes, architect solutions, and deliver production-grade software on time. Every engagement includes full documentation, NDA, and IP transfer.", IconEmoji="⚙️", KeyFeatures="[\"Requirements analysis & system design\",\"Agile delivery with 2-week sprints\",\"Code review & quality gates\",\"Full test coverage (unit + integration)\",\"Deployment & handover support\",\"3-month post-launch warranty\"]", TechStack="[\"Angular 19\",\".NET 9\",\"SQL Server\",\"Azure\",\"Docker\",\"GitHub Actions\"]", SortOrder=1, IsActive=true, CreatedAt=new DateTime(2024,1,1) },
            new Service { Id=2, Slug="web-application-development", Title="Web Application Development", Tagline="Fast, scalable, production-ready", ShortDescription="Modern web applications built with Angular 19 and .NET Core 9 — designed for performance, accessibility, and long-term maintainability.", LongDescription="From customer portals to internal dashboards, we build web applications that perform at scale. Our Angular + .NET stack delivers type-safe, maintainable code. All apps are built mobile-first, accessibility-compliant, and optimised for Core Web Vitals.", IconEmoji="🌐", KeyFeatures="[\"Angular 19 standalone components\",\"Progressive Web App support\",\"REST & GraphQL APIs\",\"Role-based access control\",\"Real-time features (SignalR)\",\"CI/CD pipeline setup\"]", TechStack="[\"Angular 19\",\"TypeScript\",\".NET 9\",\"SignalR\",\"Redis\",\"PostgreSQL\"]", SortOrder=2, IsActive=true, CreatedAt=new DateTime(2024,1,1) },
            new Service { Id=3, Slug="ai-machine-learning", Title="AI & Machine Learning", Tagline="Intelligence built into your product", ShortDescription="Custom AI/ML solutions — document intelligence, predictive analytics, NLP, and computer vision — integrated into your existing systems.", LongDescription="We build practical AI that delivers measurable ROI, not demos. From document processing pipelines handling 10,000+ pages per day to recommendation engines and predictive maintenance systems.", IconEmoji="🤖", KeyFeatures="[\"Document intelligence & OCR\",\"Predictive analytics models\",\"NLP & text classification\",\"Computer vision pipelines\",\"Model monitoring & retraining\",\"Integration with existing systems\"]", TechStack="[\"Python\",\"FastAPI\",\"TensorFlow\",\"PyTorch\",\"Azure ML\",\"OpenAI API\"]", SortOrder=3, IsActive=true, CreatedAt=new DateTime(2024,1,1) },
            new Service { Id=4, Slug="mobile-app-development", Title="Mobile App Development", Tagline="iOS & Android from a single codebase", ShortDescription="Cross-platform mobile apps built with Flutter or React Native — native performance, beautiful UI, single team for both platforms.", LongDescription="We deliver mobile apps that users love. Cross-platform approach means fully native iOS and Android apps from a single codebase. App Store and Play Store submission handled end-to-end.", IconEmoji="📱", KeyFeatures="[\"Flutter & React Native\",\"Offline-first architecture\",\"Push notifications\",\"Biometric authentication\",\"App Store & Play Store submission\",\"Analytics & crash reporting\"]", TechStack="[\"Flutter\",\"React Native\",\"Firebase\",\"REST APIs\",\".NET Backend\",\"SQLite\"]", SortOrder=4, IsActive=true, CreatedAt=new DateTime(2024,1,1) },
            new Service { Id=5, Slug="cloud-devops", Title="Cloud & DevOps", Tagline="99.99% uptime, zero compromise", ShortDescription="Cloud migration, infrastructure automation, and DevOps transformation on Azure, AWS, or GCP.", LongDescription="We help engineering teams move fast without breaking things. From cloud migrations to Kubernetes clusters and fully automated CI/CD pipelines, we bring DevOps maturity to your organisation.", IconEmoji="☁️", KeyFeatures="[\"Cloud migration (Azure/AWS/GCP)\",\"Kubernetes & Docker orchestration\",\"CI/CD pipeline design\",\"Infrastructure as Code (Terraform)\",\"Cost optimisation\",\"24x7 managed infrastructure\"]", TechStack="[\"Azure\",\"AWS\",\"Kubernetes\",\"Terraform\",\"Docker\",\"GitHub Actions\"]", SortOrder=5, IsActive=true, CreatedAt=new DateTime(2024,1,1) },
            new Service { Id=6, Slug="cybersecurity-compliance", Title="Cybersecurity & Compliance", Tagline="ISO 27001 · GDPR · RBI compliant", ShortDescription="Security audits, penetration testing, and compliance implementation for BFSI and enterprise clients.", LongDescription="Our cybersecurity practice helps organisations achieve and maintain compliance with ISO 27001, GDPR, RBI guidelines, and SEBI requirements. We combine technical security assessments with policy consulting.", IconEmoji="🛡️", KeyFeatures="[\"Security audit & gap analysis\",\"Penetration testing\",\"ISO 27001 implementation\",\"GDPR & RBI compliance\",\"Security awareness training\",\"Incident response planning\"]", TechStack="[\"SIEM tools\",\"Kali Linux\",\"Burp Suite\",\"AWS Security Hub\",\"Azure Defender\",\"OWASP ZAP\"]", SortOrder=6, IsActive=true, CreatedAt=new DateTime(2024,1,1) }
        );

        modelBuilder.Entity<BlogPost>().HasData(
            new BlogPost { Id=1, Slug="angular-19-signals-complete-guide", Title="Angular 19 Signals: The Complete Guide for Enterprise Apps", Excerpt="Signals replace RxJS for most state management needs in Angular 19. Here's what that means for large-scale applications.", Category="Angular & .NET Core", AuthorName="Ravi Kumar", ReadTimeMinutes=8, IsPublished=true, PublishedAt=new DateTime(2025,2,10), ViewCount=2341, Content="<h2>Why Signals change everything</h2><p>Angular 19's signals system fundamentally shifts how we think about reactivity in large applications. Instead of observables that can be complex to manage, signals offer a simpler, more predictable model.</p><h2>Key benefits for enterprise</h2><p>For enterprise applications, signals bring three key advantages: predictable change detection, simpler debugging, and better performance out of the box.</p>", CreatedAt=new DateTime(2025,2,10) },
            new BlogPost { Id=2, Slug="dotnet-9-minimal-api-vs-controllers", Title=".NET 9 Minimal APIs vs Controllers: When to Use Which", Excerpt="Minimal APIs are not a replacement for controllers in enterprise applications. Here's the nuanced decision framework we use at TechSolve.", Category="Angular & .NET Core", AuthorName="Priya Nair", ReadTimeMinutes=6, IsPublished=true, PublishedAt=new DateTime(2025,1,22), ViewCount=1876, Content="<h2>The false dichotomy</h2><p>The .NET community often presents this as a binary choice. It isn't. In practice, both approaches coexist in the same application depending on the use case.</p><h2>When Controllers still win</h2><p>For complex APIs with action filters, model validation attributes, and rich Swagger documentation, controllers remain more expressive.</p>", CreatedAt=new DateTime(2025,1,22) },
            new BlogPost { Id=3, Slug="ai-document-processing-bfsi", Title="How We Built an AI Document Pipeline Processing 50,000 Pages Per Day", Excerpt="A practical walkthrough of the architecture behind a production document intelligence system built for a leading Indian insurer.", Category="AI & Machine Learning", AuthorName="Karan Mehta", ReadTimeMinutes=12, IsPublished=true, PublishedAt=new DateTime(2025,1,8), ViewCount=4120, Content="<h2>The problem</h2><p>Our client — a top-5 Indian insurance company — was processing 50,000 policy documents per day manually. Turnaround time was 48 hours. Error rate was 4.2%. The business needed sub-2-hour processing with under 0.1% errors.</p><h2>The results</h2><p>After 90 days in production: average processing time dropped to 23 minutes, error rate fell to 0.08%, and the client reallocated 34 full-time employees to higher-value work.</p>", CreatedAt=new DateTime(2025,1,8) }
        );
    }
}
