// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechSolve.DataModel;

#nullable disable

namespace TechSolve.DataModel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404143311_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TechSolve.Domain.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Ravi Kumar",
                            Category = "Angular & .NET Core",
                            Content = "<h2>Why Signals change everything</h2><p>Angular 19's signals system fundamentally shifts how we think about reactivity in large applications. Instead of observables that can be complex to manage, signals offer a simpler, more predictable model.</p><h2>Key benefits for enterprise</h2><p>For enterprise applications, signals bring three key advantages: predictable change detection, simpler debugging, and better performance out of the box.</p>",
                            CreatedAt = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Excerpt = "Signals replace RxJS for most state management needs in Angular 19. Here's what that means for large-scale applications.",
                            IsDeleted = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReadTimeMinutes = 8,
                            Slug = "angular-19-signals-complete-guide",
                            Title = "Angular 19 Signals: The Complete Guide for Enterprise Apps",
                            ViewCount = 2341
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Priya Nair",
                            Category = "Angular & .NET Core",
                            Content = "<h2>The false dichotomy</h2><p>The .NET community often presents this as a binary choice. It isn't. In practice, both approaches coexist in the same application depending on the use case.</p><h2>When Controllers still win</h2><p>For complex APIs with action filters, model validation attributes, and rich Swagger documentation, controllers remain more expressive.</p>",
                            CreatedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Excerpt = "Minimal APIs are not a replacement for controllers in enterprise applications. Here's the nuanced decision framework we use at TechSolve.",
                            IsDeleted = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReadTimeMinutes = 6,
                            Slug = "dotnet-9-minimal-api-vs-controllers",
                            Title = ".NET 9 Minimal APIs vs Controllers: When to Use Which",
                            ViewCount = 1876
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Karan Mehta",
                            Category = "AI & Machine Learning",
                            Content = "<h2>The problem</h2><p>Our client — a top-5 Indian insurance company — was processing 50,000 policy documents per day manually. Turnaround time was 48 hours. Error rate was 4.2%. The business needed sub-2-hour processing with under 0.1% errors.</p><h2>The results</h2><p>After 90 days in production: average processing time dropped to 23 minutes, error rate fell to 0.08%, and the client reallocated 34 full-time employees to higher-value work.</p>",
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Excerpt = "A practical walkthrough of the architecture behind a production document intelligence system built for a leading Indian insurer.",
                            IsDeleted = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReadTimeMinutes = 12,
                            Slug = "ai-document-processing-bfsi",
                            Title = "How We Built an AI Document Pipeline Processing 50,000 Pages Per Day",
                            ViewCount = 4120
                        });
                });

            modelBuilder.Entity("TechSolve.Domain.Entities.Enquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePageTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ServiceSlug");

                    b.HasIndex("Status");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("TechSolve.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconEmoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyFeatures")
                        .HasColumnType("TEXT");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechStack")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IconEmoji = "⚙️",
                            IsActive = true,
                            IsDeleted = false,
                            KeyFeatures = "[\"Requirements analysis & system design\",\"Agile delivery with 2-week sprints\",\"Code review & quality gates\",\"Full test coverage (unit + integration)\",\"Deployment & handover support\",\"3-month post-launch warranty\"]",
                            LongDescription = "We design and build software that fits your business precisely — not a generic product forced to adapt. Our senior engineers work with you to map processes, architect solutions, and deliver production-grade software on time. Every engagement includes full documentation, NDA, and IP transfer.",
                            ShortDescription = "Bespoke applications engineered for your unique business processes — from complex enterprise workflows to greenfield SaaS platforms.",
                            Slug = "custom-software-development",
                            SortOrder = 1,
                            Tagline = "Built for your exact requirements",
                            TechStack = "[\"Angular 19\",\".NET 9\",\"SQL Server\",\"Azure\",\"Docker\",\"GitHub Actions\"]",
                            Title = "Custom Software Development"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IconEmoji = "🌐",
                            IsActive = true,
                            IsDeleted = false,
                            KeyFeatures = "[\"Angular 19 standalone components\",\"Progressive Web App support\",\"REST & GraphQL APIs\",\"Role-based access control\",\"Real-time features (SignalR)\",\"CI/CD pipeline setup\"]",
                            LongDescription = "From customer portals to internal dashboards, we build web applications that perform at scale. Our Angular + .NET stack delivers type-safe, maintainable code. All apps are built mobile-first, accessibility-compliant, and optimised for Core Web Vitals.",
                            ShortDescription = "Modern web applications built with Angular 19 and .NET Core 9 — designed for performance, accessibility, and long-term maintainability.",
                            Slug = "web-application-development",
                            SortOrder = 2,
                            Tagline = "Fast, scalable, production-ready",
                            TechStack = "[\"Angular 19\",\"TypeScript\",\".NET 9\",\"SignalR\",\"Redis\",\"PostgreSQL\"]",
                            Title = "Web Application Development"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IconEmoji = "🤖",
                            IsActive = true,
                            IsDeleted = false,
                            KeyFeatures = "[\"Document intelligence & OCR\",\"Predictive analytics models\",\"NLP & text classification\",\"Computer vision pipelines\",\"Model monitoring & retraining\",\"Integration with existing systems\"]",
                            LongDescription = "We build practical AI that delivers measurable ROI, not demos. From document processing pipelines handling 10,000+ pages per day to recommendation engines and predictive maintenance systems.",
                            ShortDescription = "Custom AI/ML solutions — document intelligence, predictive analytics, NLP, and computer vision — integrated into your existing systems.",
                            Slug = "ai-machine-learning",
                            SortOrder = 3,
                            Tagline = "Intelligence built into your product",
                            TechStack = "[\"Python\",\"FastAPI\",\"TensorFlow\",\"PyTorch\",\"Azure ML\",\"OpenAI API\"]",
                            Title = "AI & Machine Learning"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IconEmoji = "📱",
                            IsActive = true,
                            IsDeleted = false,
                            KeyFeatures = "[\"Flutter & React Native\",\"Offline-first architecture\",\"Push notifications\",\"Biometric authentication\",\"App Store & Play Store submission\",\"Analytics & crash reporting\"]",
                            LongDescription = "We deliver mobile apps that users love. Cross-platform approach means fully native iOS and Android apps from a single codebase. App Store and Play Store submission handled end-to-end.",
                            ShortDescription = "Cross-platform mobile apps built with Flutter or React Native — native performance, beautiful UI, single team for both platforms.",
                            Slug = "mobile-app-development",
                            SortOrder = 4,
                            Tagline = "iOS & Android from a single codebase",
                            TechStack = "[\"Flutter\",\"React Native\",\"Firebase\",\"REST APIs\",\".NET Backend\",\"SQLite\"]",
                            Title = "Mobile App Development"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IconEmoji = "☁️",
                            IsActive = true,
                            IsDeleted = false,
                            KeyFeatures = "[\"Cloud migration (Azure/AWS/GCP)\",\"Kubernetes & Docker orchestration\",\"CI/CD pipeline design\",\"Infrastructure as Code (Terraform)\",\"Cost optimisation\",\"24x7 managed infrastructure\"]",
                            LongDescription = "We help engineering teams move fast without breaking things. From cloud migrations to Kubernetes clusters and fully automated CI/CD pipelines, we bring DevOps maturity to your organisation.",
                            ShortDescription = "Cloud migration, infrastructure automation, and DevOps transformation on Azure, AWS, or GCP.",
                            Slug = "cloud-devops",
                            SortOrder = 5,
                            Tagline = "99.99% uptime, zero compromise",
                            TechStack = "[\"Azure\",\"AWS\",\"Kubernetes\",\"Terraform\",\"Docker\",\"GitHub Actions\"]",
                            Title = "Cloud & DevOps"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IconEmoji = "🛡️",
                            IsActive = true,
                            IsDeleted = false,
                            KeyFeatures = "[\"Security audit & gap analysis\",\"Penetration testing\",\"ISO 27001 implementation\",\"GDPR & RBI compliance\",\"Security awareness training\",\"Incident response planning\"]",
                            LongDescription = "Our cybersecurity practice helps organisations achieve and maintain compliance with ISO 27001, GDPR, RBI guidelines, and SEBI requirements. We combine technical security assessments with policy consulting.",
                            ShortDescription = "Security audits, penetration testing, and compliance implementation for BFSI and enterprise clients.",
                            Slug = "cybersecurity-compliance",
                            SortOrder = 6,
                            Tagline = "ISO 27001 · GDPR · RBI compliant",
                            TechStack = "[\"SIEM tools\",\"Kali Linux\",\"Burp Suite\",\"AWS Security Hub\",\"Azure Defender\",\"OWASP ZAP\"]",
                            Title = "Cybersecurity & Compliance"
                        });
                });

            modelBuilder.Entity("TechSolve.Domain.Entities.WhatsAppTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClickSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Referrer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceSlug")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ServiceSlug");

                    b.ToTable("WhatsAppTrackings");
                });
#pragma warning restore 612, 618
        }
    }
}
