name: Deploy to MonsterASP.NET

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy .NET API
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Setup .NET 9
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      # 3. Restore dependencies
      - name: Restore
        run: dotnet restore TechSolve.sln

      # 4. Publish release build
      - name: Publish
        run: dotnet publish TechSolve.API/TechSolve.API.csproj -c Release -o ./publish  --no-restore

      # 5. Deploy to MonsterASP via FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: site61988.siteasp.net
          username: site61988
          password: W?a98hG_t@5K
          local-dir: ./publish/
          server-dir: /
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            techsolve.db
